### ISSUE TITLE
Create the repository

### ISSUE THREAD

**Issue by jramiresbrito** [jramiresbrito/grad_software_design_homework_1#1]
## Comments
Create the repository for homework 1, A.K.A `LAB 1`.

## Tasks
- [ ] Create the local repository
   - [ ] Create a sub folder named `projeto`
   - [ ] Create a sub folder named `implementacao`
- [ ] Create the remote repository
- [ ] Push to remote
- [ ] Post the remote link on CANVAS
