### ISSUE TITLE
Create the repository

### ISSUE THREAD

**Issue by jramiresbrito** [jramiresbrito/grad_software_design_homework_1#1]
## Tasks
- [x] Create the local repository
  - [x] Add sub-folders `projeto` and `implementacao`
  - [x] Add README
- [x] Create the remote repository
- [x] Post the remote repository link on CANVAS
