### ISSUE TITLE
User Case Diagram

### ISSUE THREAD

**Issue by jramiresbrito** [jramiresbrito/grad_software_design_homework_1#2]
## Comments
Following the system described in [README.MD](https://github.com/jramiresbrito/grad_software_design_homework_1/blob/master/README.md), create the User Case Diagram.

## Tasks
- [ ] Identify the system classes
   - [ ]  Identify the classes attributes and methods
- [ ] Create the diagram
