### ISSUE TITLE
Create the User Stories

### ISSUE THREAD

**Issue by jramiresbrito** [jramiresbrito/grad_software_design_homework_1#3]
## Comments
Based on the described system specifications, add on [README](https://github.com/jramiresbrito/grad_software_design_homework_1/blob/master/README.md) the `User Stories` following the formula:

> As an `Actor`, I can do the `Task`, so I can achieve the `Goal`

## Tasks
- [ ] Identify the system Actors
- [ ] Identify the Goals
- [ ] Write the User Stories
