### ISSUE TITLE
ADD Class Diagram

### ISSUE THREAD

**Issue by jramiresbrito** [jramiresbrito/grad_software_design_homework_1#4]
## Comments
Follow the description present on [README](https://github.com/jramiresbrito/grad_software_design_homework_1/blob/master/README.md)

## Tasks
- [ ] Identify the system classes
    - [ ]  Identify the class attributes
    - [ ]  Identify the class methods
- [ ] Create the diagram
