### ISSUE TITLE
Create the Java Project

### ISSUE THREAD

**Issue by jramiresbrito** [jramiresbrito/grad_software_design_homework_1#5]
## Tasks
- [ ] Create the project inside the folder `implementacao`
- [ ] Add the first classes
   - [ ] Add class attributes
   - [ ] Add class methods
